package se.yrgo.dataaccess;

import org.springframework.dao.DuplicateKeyException;
import org.springframework.dao.EmptyResultDataAccessException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.RowMapper;
import se.yrgo.domain.Call;
import se.yrgo.domain.Customer;
import se.yrgo.services.customers.CustomerAlreadyExistsException;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.List;

public class CustomerDaoJdbcTemplateImpl implements CustomerDao {

    private static final String DELETE_SQL = "DELETE FROM CUSTOMER WHERE CUSTOMER_ID=?";
    private static final String UPDATE_SQL = "UPDATE CUSTOMER SET COMPANY_NAME=?, EMAIL=?, TELEPHONE=?, NOTES=? WHERE CUSTOMER_ID=?";
    private static final String INSERT_SQL = "INSERT INTO CUSTOMER(CUSTOMER_ID, COMPANY_NAME, EMAIL, TELEPHONE, NOTES) VALUES (?,?,?,?,?)";
    private static final String GET_BY_ID_SQL = "SELECT * FROM CUSTOMER WHERE CUSTOMER_ID=?";
    private static final String GET_BY_NAME_SQL = "SELECT * FROM CUSTOMER WHERE COMPANY_NAME=?";
    private static final String GET_ALL_SQL = "SELECT * FROM CUSTOMER";
    private static final String ADD_CALL_SQL = "INSERT INTO CALLS(TIME_AND_DATE, NOTES, CUSTOMER_ID) VALUES (?,?,?)";
    private static final String GET_CALLS_BY_CUSTOMER_ID = "SELECT * FROM CALLS WHERE CUSTOMER_ID=?";

    JdbcTemplate template;

    public CustomerDaoJdbcTemplateImpl(JdbcTemplate template) {
        this.template = template;
        createTables();
    }

    @Override
    public void createTables() {

        this.template.update("""
                CREATE TABLE IF NOT EXISTS CUSTOMER (
                    CUSTOMER_ID VARCHAR(50) PRIMARY KEY,
                    COMPANY_NAME VARCHAR(100) NOT NULL,
                    EMAIL VARCHAR(100),
                    TELEPHONE VARCHAR(30),
                    NOTES VARCHAR(255) NOT NULL
                );
                """);

        this.template.update("""
                CREATE TABLE IF NOT EXISTS CALLS (
                    CALL_ID INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
                    TIME_AND_DATE TIMESTAMP NOT NULL,
                    NOTES VARCHAR(255) NOT NULL,
                    CUSTOMER_ID VARCHAR(50) NOT NULL,
                    CONSTRAINT FK_CALLS_CUSTOMER
                        FOREIGN KEY (CUSTOMER_ID)
                        REFERENCES CUSTOMER(CUSTOMER_ID)
                );
                """);
    }

    @Override
    public void clearTables() {
        this.template.update("DELETE FROM CALLS");
        this.template.update("DELETE FROM CUSTOMER");
    }

    @Override
    public void create(Customer customer) {
        try {
            template.update(INSERT_SQL,
                    customer.getCustomerId(),
                    customer.getCompanyName(),
                    customer.getEmail(),
                    customer.getTelephone(),
                    customer.getNotes());
        } catch (DuplicateKeyException e) {
            throw new CustomerAlreadyExistsException("Customer: " + customer.getCustomerId() + " already exists!");
        }
    }

    @Override
    public Customer getById(String customerId) throws RecordNotFoundException {
        try {
            return template.queryForObject(GET_BY_ID_SQL, new CustomerRowMapper(), customerId);
        } catch (EmptyResultDataAccessException e) {
            throw new RecordNotFoundException();
        }
    }

    @Override
    public List<Customer> getByName(String name) {
        return this.template.query(GET_BY_NAME_SQL, new CustomerRowMapper(), name);
    }

    @Override
    public void update(Customer customerToUpdate) throws RecordNotFoundException {
        int rows = this.template.update(
                UPDATE_SQL,
                customerToUpdate.getCompanyName(),
                customerToUpdate.getEmail(),
                customerToUpdate.getTelephone(),
                customerToUpdate.getNotes(),
                customerToUpdate.getCustomerId()
        );

        if (rows == 0) {
            throw new RecordNotFoundException();
        }
    }

    @Override
    public void delete(Customer oldCustomer) throws RecordNotFoundException {
        int rows = this.template.update(DELETE_SQL, oldCustomer.getCustomerId());
        if (rows == 0) {
            throw new RecordNotFoundException();
        }
    }

    @Override
    public List<Customer> getAllCustomers() {
        return this.template.query(GET_ALL_SQL, new CustomerRowMapper());
    }

    @Override
    public Customer getFullCustomerDetail(String customerId) throws RecordNotFoundException {
        Customer customer = getById(customerId);
        List<Call> calls = template.query(GET_CALLS_BY_CUSTOMER_ID, new CallRowMapper(), customerId);
        customer.setCalls(calls);
        return customer;
    }

    @Override
    public void addCall(Call newCall, String customerId) throws RecordNotFoundException {
        this.template.update(ADD_CALL_SQL, newCall.getTimeAndDate(), newCall.getNotes(), customerId);
    }
}

class CustomerRowMapper implements RowMapper<Customer> {
    public Customer mapRow(ResultSet rs, int arg1) throws SQLException {
        String customerId = rs.getString(1);
        String companyName = rs.getString(2);
        String email = rs.getString(3);
        String telephone = rs.getString(4);
        String notes = rs.getString(5);

        return new Customer(customerId, companyName, email, telephone, notes);
    }
}

class CallRowMapper implements RowMapper<Call> {
    public Call mapRow(ResultSet rs, int arg1) throws SQLException {
        int callId = rs.getInt(1);
        Date timeAndDate = rs.getDate(2);
        String notes = rs.getString(3);

        return new Call(notes, timeAndDate);
    }
}
